repos:
- repo: local
  hooks:
  - id: flake8
    name: flake8
    entry: flake8
    language: system
    verbose: true
    pass_filenames: true
    files: src/*.py tests/*.py
  - id: black
    name: black
    entry: black
    language: system
    verbose: true
    files: src/*.py tests/*.py
    pass_filenames: true
