repos:
- repo: local
  hooks:
  - id: flake8
    name: flake8 for src
    entry: flake8
    language: system
    verbose: true
    pass_filenames: true
    files: src/gh.py
  - id: black
    name: black for src
    entry: black
    language: system
    verbose: true
    pass_filenames: true
    files: src/gh.py
